@startsalt
{+
  Період         | "Поточний тиждень"
  Попередній     | "Минулого тижня"
  Порівняння:
  "Активність: +10%"
  "Сон: -5%"
  "Калорії: стабільно"
  [Показати графік] | [  Завантажити CSV  ]
}
@endsalt
