name: Program Code Convention Check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ProgramCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code from Repository
        uses: actions/checkout@v3

      - name: Run Java Code Convention Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVA: true
          FILTER_REGEX_INCLUDE: .*/ProgramCode\.java
